version: "2"
services:
  nginx:
    image: docker.io/nginx
    ports: 
    - 80:80
    volumes:
    - ~/go-blog/view:/usr/share/nginx/html
    restart: unless-stopped

  blog:
    image: spider1998/go-blog:v3
    ports:
    - 8081:8081
    volumes:
        - ~/go-blog/attachment:/Project/doit/attachment
    env_file:
        - ~/go-blog/env/blog.env
    restart: unless-stopped

  mysql:
    image: mysql:5.7.16
    ports:
    - 3306:3306
    environment:
        - TZ=Asia/Shanghai
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=doit
    volumes:
        - ~/go-blog/mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped

  redis:
    image: redis:3
    ports:
    - 6379:6379
    restart: unless-stopped

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    restart: unless-stopped

  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
    - 4150:4150
    restart: unless-stopped
